### ISSUE TITLE
Fails install with laravel 5.0 due to dependency issue

### ISSUE THREAD

**Issue by jwilson8767** [adamkearsley/laravel-convert-migrations#12]
Dependencies are out of date and therefore attempting to install with laravel 5.0 fails.

Composer update results in:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for adamkearsley/convert-migrations dev-master -> satisfiable by adamkearsley/convert-migrations[dev-master].
    - Conclusion: remove laravel/framework v5.0.0
    - adamkearsley/convert-migrations dev-master requires illuminate/console 4.2.* -> satisfiable by illuminate/console[v4.2.1, v4.2.12, v4.2.16, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/console v4.2.1|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.12|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.16|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.2|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.3|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.4|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.5|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.8|don't install laravel/framework v5.0.0
    - don't install illuminate/console v4.2.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[v5.0.0].

**Comment by christoferw** [comment]
i got same with laravel 5

**Comment by brunowego** [comment]
+1

**Comment by youyi1314** [comment]
+1

**Comment by adamkearsley** [comment]
Sorry I'm no longer looking after this, please FORK for L5 :)
